### ISSUE TITLE
Error rendering trend - property 'boundary' of undefined

### ISSUE THREAD

**Issue by pongoman** [QingWei-Li/vue-trend#1]
Hi, I am having some trouble with this. Installed and got the following error.

![error](https://cloud.githubusercontent.com/assets/14333747/23872794/5107731a-0838-11e7-9aa5-c272781d5f54.png)

Project created through vue-cli webpack template

`main.js`

`import Trend from 'vuetrend`' 
`Vue.use(Trend)`

Template in `app.vue` as shown in the first example
Thanks

**Comment by QingWei-Li** [comment]
https://jsfiddle.net/nyh18bLq/

Hi, It's working for me. Can you provide a demo?

**Comment by pongoman** [comment]
I started a fresh project with latest vue-cli wepack template and it worked. I couldn't pinpoint the problem though. Maybe something with older versions..

Thank you and sorry for this :) Closing
