### ISSUE TITLE
Error when using Trend in Meteor

### ISSUE THREAD

**Issue by iojanis** [QingWei-Li/vue-trend#14]
W20180124-18:10:58.424(1)? (STDERR) [Vue warn]: Error in nextTick: "TypeError: Cannot read property '$el' of undefined"
W20180124-18:10:58.425(1)? (STDERR) 
W20180124-18:10:58.425(1)? (STDERR) found in
W20180124-18:10:58.425(1)? (STDERR) 
W20180124-18:10:58.426(1)? (STDERR) ---> <Trend>
W20180124-18:10:58.426(1)? (STDERR)        <Terminal>
W20180124-18:10:58.426(1)? (STDERR)          <Root>
W20180124-18:10:58.426(1)? (STDERR) (node:3903) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property '$el' of undefined

**Comment by aaronhuisinga** [comment]
I am receiving this same error after updating to v0.3.1.

My code is as follows:
```
        <trend
            :data="list.trend_data"
            :gradient="['#f8f8f8', '#f8f8f8']"
            preserveAspectRatio="xMidYMid slice"
            viewBox="0 0 300 100"
            auto-draw
            smooth>
        </trend>
```
