### ISSUE TITLE
vue warning

### ISSUE THREAD

**Issue by pici** [QingWei-Li/vue-trend#4]
great lib !

that's my HTML part:
`<trend
                :data="data"
                :gradient="['#6fa8dc', '#42b983', '#2c3e50']"
                auto-draw
                auto-draw-duration='1500'
              auto-draw-easing="ease-in">
</trend>`

I got following warning:
[Vue warn]: Invalid prop: type check failed for prop "autoDrawDuration". Expected Number, got String. 
(found in <Trend>)

anyway it's working - there is effect when i change auto-draw-duration value.

**Comment by QingWei-Li** [comment]
:auto-draw-duration='1500'

**Comment by pici** [comment]
got it !
Thanks a lot.

brgds
