### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by korpa** [QingWei-Li/vue-trend#5]
Hi,

there seems to be a scaling issue if you have too similar values. In this case you line is shown: https://jsfiddle.net/o8q2jeu6/1/

If you just replace one data point with a value that differs much more from the average, then the line is shown properly (I replaced the first "22" with "1"): https://jsfiddle.net/o8q2jeu6/2/

Could you please have look into this?

**Comment by vesakk** [comment]
Hi,

Awesome lib!!!!

Anything about this bug?

**Comment by olivbau** [comment]
Hey, @vesakk is right, ths lib is Awesome !

Anything new about this bug ?

**Comment by vesakk** [comment]
Hi @olivbau ,

I like your temp solution!

**Comment by baubie** [comment]
Normalizing the data works sometimes but not always.  I found that adding a dummy value at the front that was outside the range of other values always fixed the issue, but now you're plotting a fake piece of data.

**Comment by RainySeattle** [comment]
数据稍微大一点比如 [ 300, 301, 302, 302 ], 路径就会飘到上面去了，完全看不到，必须得以一个很小的数字作为第一个数据，比如 [0, 300, 301, 302, 302 ] 才能绘图正常。

**Comment by santiagomalter** [comment]
I have the same issue. When three values are similar in a row, the chart won't load.
